[package]
name = "tarnished"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
tui = "0.19"
crossterm = "0.25"
tui-textarea = "0.2.0"
clap = "~2.27.0"
anyhow = "1.0.68"
bio = "1.1.0"